model:
  best_model: RandomForest
  feature_sets:
    rfe:
    - num__sqft
    - num__bathrooms
    - num__house_age
    - num__price_per_sqft
    - num__bed_bath_ratio
    - cat__location_Suburb
    - cat__condition_Excellent
    - cat__condition_Fair
    - cat__condition_Good
    - cat__condition_Poor
  mae: 12855.625
  name: house_price_model
  parameters:
    bootstrap: true
    ccp_alpha: 0.0
    criterion: squared_error
    max_depth: null
    max_features: 1.0
    max_leaf_nodes: null
    max_samples: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    monotonic_cst: null
    n_estimators: 100
    n_jobs: null
    oob_score: false
    random_state: null
    verbose: 0
    warm_start: false
  r2_score: 0.9922703235467367
  target_variable: price
